# -*- coding: utf-8 -*-
import random

class IndividualMission:
    
    part_01 = [
        "Bribe", "Bring message to location of", 
        "Capture or arrest", "Conceal", "Deliver", 
        "Discover identity of", "Distract", "Deceive", "Transport"
        "Entrap", "Extort from", "Find missing", 
        "Get help from", "Guard", "Incriminate", 
        "Kidnap", "Kill", "Rescue", "Frame", "Decoy",
        "Sabotage efforts of", "Spy upon", "Steal item from",
        "Waylay", "Negotiate with", "Sting" , "Smuggle", "Protect",
        "Assassinate"
        ]

    part_02 = [
        "Astrologer (skillful)","Poseur", "Abbot (Asian-style monk)",
        "Abbot (European-style)", "Abbot (heretic)", "Accused person (guilty)", 
        "Accused person (innocent)", 
        "Accuser killer (roll a second time for victim’s identity, if desired)", 
        "Actor (famous)", "Actor (leader of troupe)", "Actor (minor)", 
        "Addict (alcohol)","Addict (drugs)", "Addict (gambling)",
        "Addict (love)", "Addict (music)","Addict (opium or hashish)", 
        "Addict (other)","Adulterer","Adulterer (suspected)", 
        "Adventurer (cleric)", "Adventurer (fighter)", "Adventurer (magic-user)", 
        "Adventurer (thief)", "Adventurer(s)", "Agent (of deity)",
        "Agent (of demon)", "Agent (of fate)", "Agent (of guild)", 
        "Agent (of merchant house)", "Agent (of mercy)", "Agent (of sultan)", 
        "Agent (of the king)", "Agent (secret diplomat)", "Agent (secret police)", 
        "Agent (spy) Alchemist", "Agent or diplomat", "Alchemist (with secret formula)", 
        "Almoner (collecting alms)", "Almoner (dispensing alms)", "Almoner (embezzlement suspect)",
        "Ambassador (commercial or mercantile)", "Ambassador (local political)", 
        "Ambassador (major political)", "Anarchist (at work)", 
        "Anarchist (scheming)", "Anarchist (suspected)", "Anarcho-syndicalist peasant", 
        "Animal trainer (normal animals)","Animal trainer (unusual animals)", 
        "Anonymous wretch", "Apothecary (illegal or unlicensed)", 
        "Apothecary (legal)", "Apprentice (mundane craft)", 
        "Apprentice (thief or assassin)", "Apprentice (wizard or alchemist)", 
        "Architect (any)", "Architect (castle)", "Architect (dungeons or prison)", 
        "Architect (palace)", "Archivist (births and deaths)", 
        "Archivist (city or town history)", "Archivist (criminal records)", 
        "Archivist (heraldry and lineage)", "Archivist (land rights)", 
        "Archivist (noble family)", "Archivist (temple)", 
        "Arena owner", "Armorer (famous)", "Armorer (skilled)",
        "Artificer (lenses and glass)", "Artificer (siege engines)",
        "Artificer (water power or aqueducts)", "Artisan (any)", "Artisan (glass)", 
        "Assassin (currently employed)", "Assassin (not employed)", 
        "Assistant or supporter (unauthorized)","Astrologer (charlatan)", 
        "Astrologer (in hiding)","Auction-house owner Author (lascivious verse)", 
        "Author (philosophical)", "Author (satirical)","Author (spell book or magic tome)", 
        "Bailiff (courtroom)","Bailiff (sheriff’s official serving writs, process)",
        "Baker", "Bandit (highwayman)","Bandit (leader)", "Bandit (lone)", 
        "Bandit (popular hero)", "Bandit (with stolen treasure)", "Barbarian", 
        "Barber", "Bard (on mission)", "Bard (traveling minstrel)", 
        "Baron (poor)", "Baron (rich)", "Baroness (beautiful)", "Baroness (cruel)", 
        "Baroness (ugly)", "Bazaar owner","Beadle (major temple)", 
        "Beadle (minor temple)", "Beadle (of heretical temple)", "Beggar (crippled)", 
        "Beggar (normal)", "Beggar (secret identity)", "Beggar (thief)", 
        "Beggar (witness)", "Bird catcher (fabulous and magical birds)", 
        "Bird catcher (falcons)", "Bird catcher (game birds)", "Bird catcher (songbirds)", 
        "Blackmailer (highly successful)", "Blackmailer (knows of crime)", 
        "Blackmailer (of evil target)", "Blackmailer (political secret)", 
        "Blackmailer (sexual information)", "Blackmailer (temple secret)", 
        "Blacksmith", "Blasphemer", "Blind man", "Bodyguard (failed)", 
        "Bodyguard (working)", "Bookseller", "Bounty hunter (congenial)", 
        "Bounty hunter (debtors)", "Bounty hunter (escaped slaves)", 
        "Bounty hunter (killer of criminals)", "Bounty hunter (unlicensed)", 
        "Brigand (highwayman)", "Brigand (leader)", "Brigand (local hero)", 
        "Brigand (seeking vengeance)", "Brigand (unjustly accused)", 
        "Broker (gems)", "Broker (land)", "Broker (loans)", "Broker (ship cargoes)", 
        "Broker (slaves)", "Brothel owner", "Bureaucratic official (cunning)", 
        "Bureaucratic official (diligent)", "Bureaucratic official (loyal)", 
        "Bureaucratic official (pompous)", "Burglar (retired)", 
        "Burglar (working)","Burned man Butcher (poor)", "Butcher (rich)", 
        "Butcher (sinister)", "Butterfly woman", "Buyer (of something)", 
        "Buyer (prospective)","Captain (barge)", "Captain (fishing boat)", 
        "Captain (infantry)","Captain (mercenary)","Captain (pirate)",
        "Captain (secret police)","Captain (ship)","Cartographer (skilled)", 
        "Cartographer (with vital map)", "Cattle breeder", "Cattle owner",
        "Cattle thief","Celebrity figure (artistic)", "Celebrity figure (foreign)", 
        "Celebrity figure (genius)", "Celebrity figure (in hiding or disguise)", 
        "Celebrity figure (local)", "Celebrity figure (magic-related)", 
        "Celebrity figure (sport or contest)", "Challenge recipient (cheating)", 
        "Challenge recipient (hiding)","Chef (skilled)", "Chef (trying hard)",
        "Circus owner", "Cleric (evil or chaotic)", "Cleric (good or lawful)", 
        "Cleric (rebel or heretic)", "Cleric or religious leader", 
        "Clone or simulacrum", "Clown (entertaining)", "Clown (evil)",
        "Collector (animals)", "Collector (books)", "Collector (insects)", 
        "Collector (magic items)", "Collector (minerals)", 
        "Collector (mundane items)", "Collector (plants)", 
        "Collector (unusual: souls, auras,demons, etc)", "Commander (city guard)", 
        "Commander (secret police)", "Connoisseur (dangerous experiences)", 
        "Connoisseur (meat)", "Connoisseur (men)", "Connoisseur (music)", 
        "Connoisseur (scents and perfumes)","Connoisseur (wine)", 
        "Connoisseur (women)", "Conservative", "Contest loser", 
        "Contest winner Cook", "Cooper Counselor (attorney)", "Counselor (political)",
        "Counterfeiter", "Courier (documents)", "Courier (gems)",
        "Courier (illegal substances)", "Courier (political messages)", 
        "Courier (stolen goods)","Courtesan (high class)",
        "Courtesan (low class)","Courtesan (noble)","Courtesan (witness or has secret)", 
        "Cousin of someone", "Craftsman (general)","Craftsman (glassblower)", 
        "Craftsman (magical materials)", "Crime boss (cursed)", 
        "Crime boss (second in command)", "Crime boss (taking care of business)", 
        "Crime boss (with personal problems)", "Crime boss (worried)", 
        "Criminal/outlaw", "Crippled man", "Cutpurse", 
        "Damsel (beautiful and noble)", "Damsel (commoner)", "Damsel (conniving and deceitful)", 
        "Damsel (distressed)", "Damsel (noble birth)", "Damsel (only a disguise)", 
        "Damsel (shockingly ugly)", "Damsel (unchaste)", 
        "Damsel (very intelligent, with a mission)", "Dancer (famous)", "Dancer (salacious)", 
        "Dancer (supernatural capability)", "Deaf-mute", "Defender (of moral virtue)", 
        "Defender (of the peace)", "Defender (of the poor)", 
        "Deity (very minor) in disguise", "Demigod (cursed)", 
        "Demigod (imprisoned)", "Demigod (incorporeal)", "Demonologist", 
        "Dentist", "Dentist (insane)", "Dentist (sinister)", "Deserter (army)", 
        "Deserter (criminal gang)", "Diplomat (any)", "Diplomat (commercial)", 
        "Diplomat (political)", "Disembodied voice", "Doctor (charlatan)", 
        "Doctor (general practice)", "Doctor (mystical)", "Doctor (sinister)", 
        "Doctor (specialist)", "Druid", "Drummer", "Emissary (affairs of the heart)", 
        "Emissary (commercial)", "Emissary (false)","Emissary (political)", 
        "Emissary (religious)", "Emissary (secret)", "Enchanter", 
        "Enchanter (evil)", "Enchanter (insane)", "Enchanter (non-human)", 
        "Enchanter (senile)", "Enchanter (very young)", "Enchantress (beautiful)", 
        "Enchantress (in love)", "Enchantress (non-human)", "Enchantress (reborn)", 
        "Enchantress (villainous)", "Engineer (aqueducts and water)", "Engineer (castles and temples)", 
        "Engineer (dungeon excavation)", "Engineer (sieges)","Escapee (monster’s lair)", 
        "Escapee (prison)", "Escapee (slave camp)","Escapee (wizard’s lab)", 
        "Executioner (famous)","Executioner (retired)","Executioner Executioner (disgraced)", 
        "Expert (code breaker)", "Expert (gems)","Expert (investigator)", 
        "Expert (magical substances)", "Expert (planting rumors) Expert (runes)", 
        "Expert (weapons)", "Expert (wilderness tracking)", 
        "Explorer (with secret knowledge)", "Explorer Explorer (well known)", 
        "Extortionist (blackmailer)", "Extortionist (for something other than money)",
        "Extortionist (magical threats)", "Extortionist (violent) Falconer", 
        "Falconer (unusual birds)", "Farmer (poor)","Farmer (rich)",
        "Farmer (with three daughters)", "Farmer (with one daughter)", 
        "Father or mother", "Felon (innocent)", "Felon (oppressed)", 
        "Ferryman", "Ferryman (hunchback)","Filthy peasant", 
        "Fire marshal", "Fisherman (owns boat)", "Fisherman (poor)", 
        "Flower arranger (possibly a monk)","Flower-bedecked woman", "Fool (cursed)",
        "Fool (insane)","Fool (professional)", "Foreigner (beautiful noblewoman)", 
        "Foreigner (other plane of existence)","Foreigner (sinister)", 
        "Foreigner (spy)", "Foreigner (stranded)", 
        "Foreigner (with outrageous accent)", "Forester (acorn-grubbing peasant)", 
        "Forester (forest protector)", "Forger (artworks)", 
        "Forger (documents)","Fortune-teller (annoying doom-prophet)", 
        "Fortune-teller (crone)", "Fortune-teller (fraud)", 
        "Fortune-teller (gypsy)", "Fugitive", "Gambler (deadly games)", 
        "Gambler (notorious cheat)", "Gambler (recent big losses)", 
        "Gambler (recent big winnings)", "Gambler (with lucky charm)", 
        "Gambling den owner Ghost (dangerous)","Ghost (female)", 
        "Ghost (harmless apparition)", "Ghost (unquiet spirit)", 
        "Gladiator (famous)", "Gladiator (slave)", "Gladiatorial trainer",
        "Glassblower", "Goldsmith (cursed)", "Goldsmith (general)", 
        "Goldsmith (impoverished)", "Goldsmith (rich)", "Goldsmith (skilled)", 
        "Goldsmith (threatened)", "Goldsmith (with rival)", "Governor", 
        "Governor (benevolent)", "Governor (cursed)", "Governor (local)", 
        "Governor (oppressive)", "Governor (with personal problem)",
        "Grave robber (accused)", "Grave robber (avaricious)", 
        "Grave robber (necromantic purposes)", "Grave robber (terrified)", 
        "Grave robber (with curse therefrom)", "Grim reaper (yep, no kidding)", 
        "Guardian (archives)", "Guardian (bodyguard)", "Guardian (criminal evidence)", 
        "Guardian (holy book or relic)", "Guardian (of child)", 
        "Guardian (of idea or concept)", "Guardian (of magical item)", "Guardian (of place)", 
        "Guardian (other)", "Guardsman", "Guildman (high ranking)", 
        "Guildmaster (assassin)", "Guildmaster (craft)", 
        "Guildmaster (merchants)", "Guildmaster (profession)", 
        "Guildmaster (thieves)", "Guildsman (loyal and hardworking)", 
        "Guildsman (secret freelancer)", "Gypsy (adventurer)", 
        "Gypsy (beautiful)", "Gypsy (crone)", 
        "Half-breed", "Hangman (loves his job)", 
        "Hangman (retired)", "Hangman (working in his official capacity)", 
        "Harem keeper (cruel)", "Harem keeper (dishonest)", 
        "Harem keeper (dutiful)", "Harem keeper (in his official capacity)",
        "Harem keeper (justifiably grumpy eunuch)", "Harem keeper (kind)", 
        "Harem owner", "Heir (if someone dies)",
        "Heir (to a barony)","Heir (to a fortune)", 
        "Heir (to something interesting)", "Heir (to the throne)", 
        "Heiress (lovable) Heiress (of curse)", "Heiress (of hereditary powers)", 
        "Heiress (secret)", "Heiress (sinister)",
        "Herbalist (with secret knowledge)", "Heretic Hester (with political influence)", 
        "Hidden witness Historian (ancients and demigods)", "Historian (kings and kingdoms)", 
        "Historian (magic and wizards)", "Historian (of a region)",
        "Historian (of a single famous person)","Holy man (fake)", 
        "Holy man (genuine)", "Huntsman (mythical beasts)", 
        "Huntsman (noble)", "Huntsman (people)", "Huntsman (stag and pheasant)", 
        "Illusionist", "Infidel", "Inquisitor (any sort)", 
        "Inquisitor (government)", "Inquisitor (illegal)", 
        "Inquisitor (of powerful temple)", "Intelligent monster", 
        "Investigator (curious amateur)", "Investigator (guild quality standards)", 
        "Investigator (knows too much)", "Investigator (legitimate)", 
        "Investor (lost money)","Investor (needs information)", 
        "Investor (suspects funny business)", "Jailor (prison official)", 
        "Jailor (simple turnkey)", "Jester (on the run)","Jester (sinister)", 
        "Jester (with magical powers)","Jeweler (working on a commission)",
        "Journalist", "Judge (from a past trial)","Judge (local)",
        "Judge (of a contest)", "Judge (of a tournament)","Judge (religious court)", 
        "Kidnapper (accused but innocent)", "Kidnapper (no longer has victim)", 
        "Kidnapper (still has victim)","Killer (justified)",
        "King (dead)","King (dethroned)","King (disguised)", 
        "King (distant foreign realm)","King (in hiding)", 
        "King (in official capacity)","King (insane)","King (missing)", 
        "King (of something strange)","King’s body part", 
        "Knave (inconstant in affairs of finance)", "Knave (inconstant in affairs of the heart)", 
        "Knave (inconstant in matters of secrecy)", "Knave (inconstant in matters of truthfulness)", 
        "Knight (cursed)", "Knight (disgraced)", "Knight (evil)", 
        "Knight (paladin)", "Knight (renowned)", "Knight (wandering)", 
        "Lady in waiting (dishonored)", "Lady in waiting (faithful to her lady)",
        "Lady in waiting (knows terrible secret)", "Lady in waiting (treacherous)",
        "Landlord (greedy)", "Landlord (under threat of death)", 
        "Landlord (with property problems)","Lawyer","Lawyer (carrying out terms of a will)", 
        "Lawyer (for the defense)", "Lawyer (for the prosecution)", 
        "Lawyer (in a civil suit)", "Leader of an autonomous commune", 
        "Leader of mob or riots)", "Leader of prayer group", 
        "Leader of sting or entrapment operation", "Leader of the glorious uprising", 
        "Leader of the pack", "Leader of the posse", 
        "Legislator (corrupt)", "Legislator (getting too close to the truth)", 
        "Legislator (kidnapped)", "Legislator (moral)", "Legislator (radical)", 
        "Legislator (suspicious)", "Legislator (traditionalist)", 
        "Leper (contagious)","Leper (fake)", "Leper (real)", "Local noble", 
        "Locksmith (accused of crime)", "Locksmith (magical locks)", 
        "Locksmith (skilled)", "Lord", 
        "Lord (of the dance)", "Lord (of the manor)", "Lord (of the skies)", 
        "Lord (of yon great castle)", "Lottery winner", 
        "Love doctor", "Loyal friend of someone", "Madman", 
        "Madman (cyclical madness)", "Madman (dangerous)", "Madman (obsessed)", 
        "Magic-user", "Maid", "Maid of honor", "Maiden (abandoned)", "Maiden (chaste)", 
        "Maiden (poor)", "Maiden (rich)", "Maiden (seeking to change that status)", 
        "Majordomo (for wizard)", "Majordomo (great manor)", 
        "Majordomo (large castle or fortress)", "Majordomo (of nobleman’s city residence)", 
        "Majordomo (small castle)", "Majordomo (small manor)", 
        "Man in strange mask", "Man with red or glowing eyes", "Man with unusual capability", 
        "Man with unusual legs", "Man with unusual pet", 
        "Man with unusual skin", "Man with wooden leg", 
        "Medicine man", "Member of secret police", "Mercenary (leader)", 
        "Mercenary (soldier)", "Mercenary (wounded)", 
        "Merchant (addictive substances)","Merchant (caravan member)", 
        "Merchant (caravan owner)", "Merchant (fleet owner)", 
        "Merchant (great)", "Merchant (minor)", 
        "Merchant (ship owner)", "Merchant (silks)", 
        "Merchant (sinister items)", "Merchant (spices)", 
        "Merchant (strange items)", "Merchant (sundry vices)", 
        "Merchant (wine)", "Messenger",
        "Messenger (commercial)", "Messenger (for military leader)", 
        "Messenger (for wizard)", "Messenger (love affair)", "Messenger (of death)", 
        "Messenger (of deity)", "Messenger (of noble)", 
        "Messenger (of religious leader)", "Messenger (with message for characters)", 
        "Military leader (betrayed)", "Military leader (defeated)", 
        "Military leader (victorious)", "Miller", 
        "Miller (grinds strange or magical substances)", "Miller (with three sons)", 
        "Miller (with unusual cat)", "Mine owner", 
        "Miner (crippled)", "Miner (with secret)", "Minister of defense", 
        "Minister of justice", "Minister of pomp and circumstance", 
        "Minister of the treasury", "Minstrel (poor)", 
        "Minstrel (rich)", "Minstrel (with attendant fans and followers)", 
        "Minstrel (with magic powers or instrument)", "Miser", 
        "Moneylender (victim of a swindle)", "Moneylender (victim of theft)", 
        "Moneylender (with an outstanding debt)", "Monk (European friar)", 
        "Monk (hermit)", "Monk (seeks to avenge dead master)", 
        "Monk (vow of silence)", "Monk’s talking severed head",
        "Necromancer","Noble (cursed)", "Noble (debtor)", 
        "Noble (dishonored)", "Noble (impoverished)", "Noble (in hiding)", 
        "Noble (rich)", "Noble (with disease)", "Noble (with personal problem)", 
        "Noblewoman (lovely)", "Noblewoman (protecting husband)", 
        "Noblewoman (shrewish)", "Nomad (barbarian wanderer)", 
        "Nomad (religious dervish)", "Nomad (savage tribesman)", 
        "Nomad (seeking lost homeland)", "Nomad (semi-civilized herdsman)", 
        "Obvious suspect", "Oddly familiar person", "Operator (gambling den)", 
        "Operator (public baths)", "Operator (scams)", "Opium den owner", 
        "Orchard owner", "Organizer (coronation)", "Organizer (festival)", 
        "Organizer (important wedding)", "Organizer (labor)", "Organizer (political)", 
        "Organizer (religious)", "Outlaw (hunted)", "Outlaw (repentant)", 
        "Outlaw (secret)", "Outlaw (suspected)", "Outlaw (violated taboo)", 
        "Outlaw (working in his job capacity)", "Outraged father", 
        "Outraged purchaser", "Owner of dangerous property", "Owner of magic item", 
        "Panderer (discreet servant of the nobility)", "Panderer (outlandish garb and manner)", 
        "Panderer (slave owner)", "Pardoner (fake political pardons)", 
        "Pardoner (fraud)", "Pardoner (pardons have actual effect)", 
        "Pardoner (real criminal pardons for sale)", "Partner (in crime)", 
        "Partner (in love)", "Partner in a business", "Patron (of arts)", 
        "Patron (of temple)", "Peasant (farmer)", "Peasant (oppressed)", 
        "Peasant (revolting)", "Peasant (shepherd)", "Peasant (wealthy)", 
        "Performer (biting satire)", "Performer (deadly stunts)", 
        "Performer (feats of memory and observation)", "Perfumer (discredited)", 
        "Perfumer (rich)", "Perfumer (with rival)", "Perfumer (with secret)", 
        "Person of ancient ancestry", "Person of evil ancestry", 
        "Person pure of blood", "Person who changes size", 
        "Person who countedvotes for an election","Person who hears a voice", 
        "Person who returned dead from the", "Person who returned from a mysterious journey", 
        "Person with no apparent face","Pickpocket Pikeman (city guard)",
        "Pikeman (mercenary)", "Pikeman (unemployed) Pilgrim (disguised) Pilgrim (false)", 
        "Pilgrim (seeking absolution)", "Pilgrim (seeking better luck)", 
        "Pilgrim (seeking vengeance)","Pirate (aerial)","Pirate (captain)",
        "Pirate (first mate)","Pirate (in hiding)","Pirate (sailor)",
        "Plowman", "Poacher (noble huntsman)", "Poacher (starving peasant)",
        "Poet (heroic verse)","Poet (impoverished)",
        "Poet (insane)","Poet (lovelorn)","Poet (satire)",
        "Poisoner (amateur)", "Poisoner (unemployed)", "Poisoner (working)", 
        "Police authority (guild’s police)", "Police authority (illegal police)", 
        "Police authority (informal police)", "Police authority (military police)", 
        "Police authority (public police)", "Police authority (vigilantes)", 
        "Polluter (food)", "Polluter (water)", "Poseur (as celebrity)", 
        "Poseur (as guild official)", "Poseur (as military leader)", 
        "Poseur (as political personage)", "Possessed person", 
        "Potential witness", "Potential witness (financial crime)", 
        "Potential witness (political)", 
        "Potential witness (religious)", "Potion maker", 
        "Preacher (anti-establishment, political)", "Preacher (new cult)", 
        "Preacher (pro-government)", "Preacher (return to old ways)", 
        "Preacher (sees visions)", "Preacher (social reformer)", 
        "Priest (defrocked)", "Priest (general)", "Priest (self-sacrificing)", 
        "Priest (sinful)", "Priest (with secret past)", "Priestess (accessible)", 
        "Priestess (inaccessible)", "Priestess (oracle)", "Priestess (saintly)", 
        "Prince (deposed)", "Prince (evil)", "Prince (foolish)", 
        "Prince (general)", "Prince (minor)", "Prince (unworthy)", 
        "Prince (younger son)", "Princess (has lost important item)", 
        "Princess (imprisoned)", "Princess (intriguing for power)", "Princess (kidnapped for marriage)", 
        "Princess (kidnapped for ransom)", "Princess (threatened with death)",
        "Prisoner (guilty)", "Prisoner (innocent)", "Prisoner (secretlyheld)", 
        "Prodigal son (greedy)", "Prodigal son (repentant)", 
        "Professor", "Prophet (accurate)", "Prophet (dangerous)", 
        "Prophet (deranged)", "Prophet (false)", "Prophet (heretical)", 
        "Prostitute (cultist)", "Prostitute (larcenous)", "Prostitute (vengeful)", 
        "Prostitute (with heart of gold)", "Racketeer (extortion)", 
        "Racketeer (high finance)", "Racketeer (shipping)", 
        "Ratcatcher Ranger", "Rebel (against criminal organization)", 
        "Rebel (political)", "Rebel (religious)", 
        "Rebel (without a particular cause)", "Recipient of strangechallenge", 
        "Reeve", "Refugee (from bad event)", "Refugee (from combat)", 
        "Reluctant witness", "Revolutionary", 
        "Rival (bidder)", "Rival (guild)", "Rival (in love affair)", 
        "Rival (merchant)", "Rival (noble)", "Rival (of the party)", 
        "Rival (poet or artist)", "Rival (wizards)", "Royalist", 
        "Rumormonger", "Rumormonger (punished)", "Rumormonger (suspected)", 
        "Rune-scriber", "Saboteur","Sage (astrology)", "Sage (history)", 
        "Sage (magic)", "Sage (mathematics and science)", "Sage (nature)", 
        "Sage (philosophy)", "Sage (religious lore)", 
        "Sailor", "Savage (curious)", "Savage (dangerous)", "Scholar (history)", 
        "Scholar (magic)", "Scholar (natural phenomena)", 
        "Scholar (religious lore)", "Scribe", "Secret agent or spy", 
        "Servant (in tavern of inn)", "Servant (of assassin)", 
        "Servant (of merchant)", "Servant (of military leader)", 
        "Servant (of noble)", "Servant (of priest)", 
        "Servant (of sage)", "Servant (of wizard)", 
        "Shepherd", "Sheriff (corrupt)", 
        "Sheriff (dutiful)", "Sheriff (rural)", 
        "Sheriff (sinister)", "Sheriff (with personal problems)", 
        "Shoemaker (poor)", "Shoemaker (rich)", 
        "Sin eater", "Singer (any sort)", "Singer (cursed)", 
        "Singer (famous)", "Slave (escaped)", "Slave (in general)", 
        "Slaver (specific females)", "Slaver (specific professionals)", 
        "Slaver (specific race)", "Slaver (works on commission)", 
        "Son or daughter", "Sorcerer (demagicked)", 
        "Sorcerer (political aspirations)", "Sorcerer (power in amulet)", 
        "Sorcerer (power in familiar)", "Sorcerer (power in fingernails)", 
        "Sorcerer (power in hair)", "Sorcerer (powerful)", 
        "Sorcerer (transformed)", "Sorcerer (weak)", 
        "Speaker for the ancients", "Speaker of foreign language", 
        "Speaker of the dead", "Speaker of the gods", 
        "Speaker of the king", "Spy (for criminal network)", 
        "Spy (for guild or merchant)", "Spy (for noble)", 
        "Spy (for suspicious spouse)", "Spy (for the man)", 
        "Spy (for the priesthood)", "Spy (for wizard)", 
        "Squire (for haughty knight)", "Squire (for missing or kidnapped knight)", 
        "Squire (for poor knight)", "Squire (of dead knight)", 
        "Steward (for a wizard)", "Steward (great manor)", 
        "Steward (large castle)", "Steward (noble’s city residence)", 
        "Steward (small castle)", "Steward (small manor)", 
        "Stonemason (general)", "Stonemason (knows where something is hidden in the walls)", 
        "Strumpet (married to noble)", "Strumpet (tavern wench)", 
        "Strumpet (thieves’ wench)", "Student", "Subject of a recent prophesy", 
        "Subject of an ancient prophesy (apparently)", "Subject of the inquisition", 
        "Subterranean citizen", "Survivor (assassination attempt)", 
        "Survivor (dungeon expedition)", "Survivor (wilderness expedition)", 
        "Survivor (with dangerous secret)", "Suspected witness", 
        "Swindler (accused)", "Swindler (suspected)", 
        "Swindler (working on scam)", "Swordsman", 
        "Swordsman (duelist)", "Swordsman (legendary)", 
        "Swordsman (mercenary)", "Swordsman (old)", 
        "Swordsmith (discredited)", "Swordsmith (famous)", 
        "Swordsmith (skilled)", "Swordsmith (with a family problem)", 
        "Tailor (poor)", "Tailor (to the nobility)", 
        "Tavern owner", "Tax collector (embezzler)", 
        "Tax collector (oppressive bully)", "Tax collector (working at his job)", 
        "Taxidermist (strange beasts)", "Teamster (camel driver)", 
        "Teamster (caravan leader)", "Teamster (regular wagon driver)", 
        "Teamster (strange beasts of burden)", "Teamster (strange wagons)", 
        "The half-a-man", "Theater owner", 
        "Thief (convicted)", "Thief (freelance)", 
        "Thief (guild member)", "Thief (guildmaster)", 
        "Thief (retired)", "Thief (strange series of items)", 
        "Toll bridge owner", "Toll road operator", 
        "Town drunk", "Trader (cattle)", 
        "Trader (furs)", "Trader (horses)", 
        "Trader (scrolls and books)", "Trader (strange items and oddments)", 
        "Traditionalist", "Traitor (religious)", 
        "Traitor (secret society)", "Traitor (to city)", 
        "Traitor (to guild)", "Trapper (furs)", 
        "Trapper (live animals)", "Traveler (normal)", 
        "Traveler (of planes and strange dimensions)","Traveler (stranded)", 
        "Traveler (with rumors or news)", "Trustee (building)", 
        "Trustee (item)", "Trustee (land)", 
        "Trustee (money)", "Twin", 
        "Two-headed man", "Unbelievably lucky person", 
        "Unbelievably unlucky person", "Undertaker", 
        "Unknown victim", "Unwilling witness", 
        "Usurper (criminal)", "Usurper (guild)", 
        "Usurper (political)", "Usurper (religious)", 
        "Vampire", "Vandal (unintentional)", 
        "Veiled woman", "Vendor (elixirs)", 
        "Vendor (food)","Vendor (religious charms)","Vendor (shrunken heads)",
        "Vengeful eunuch","Victim (assault)","Victim (counterfeit)",
        "Victim (kidnap)","Victim (murder)","Victim (of rumors)",
        "Victim (of slander)", "Victim (of theft)", 
        "Vigilante (against crime)", "Vigilante (political faction)", 
        "Vigilante (religious)", "Viking", 
        "Vintner (awful wine)", "Vintner (fine wines)", 
        "Voodoo priest or practitioner", "Wagoner", 
        "Wanderer", "Warden (prisoner has escaped)", 
        "Warden (with prisoner)","Warlock (dead)", 
        "Warlock (disembodied)", "Warlock (suspicious)",
        "Warlock (with rival)","Warlock (with secret agenda)",
        "Weaver (oppressed)","Weaver (rich)", 
        "Widow or widower of (roll again)", "Wife or husband of (roll again)", 
        "Witch (accused)", "Witch (crone)", 
        "Witch (working on a task)", "Witch (young and beautiful)", 
        "Witch doctor", "Wizard (cursed)", "Wizard (engaged in research)", 
        "Wizard (enslaved)", "Wizard (flamboyant)", 
        "Wizard (powerful)", "Wizard (sinister)", 
        "Wizard (weak or defeated)", "Wizard (with personal crisis)", 
        "Wizard (working on a commissioned task)", "Woman in feathery cloak", 
        "Woman with dancing bear", "Woman with snake eyes", 
        "Woodcutter", "Zealot (political)", "Zealot (religious)", "Zoo owner" 
        ]
    
    
    def __init__(self):
        pass



    def getResult(self):
        a = random.randint(0, len(self.part_01) - 1)
        b = random.randint(0, len(self.part_02) - 1)
        return self.part_01[a] + " " + self.part_02[b]
        